now

diff --git a/solidity-nojail-debian11/Makefile b/solidity-nojail-debian11/Makefile
--- a/solidity-nojail-debian11/Makefile
+++ b/solidity-nojail-debian11/Makefile
@@ -13,16 +13,16 @@ kill: ckill skill
 # CTFd Configuration #
 ######################
 
-export FULLNAME = CTFd challenge name
-export AUTHOR   = LosFuzzys
-export CATEGORY = smartcontract
+export FULLNAME  = CTFd challenge name
+export AUTHOR    = LosFuzzys
+export CATEGORY  = smartcontract
 define DESC
 This is a multiline challenge description!
 
 Feel free to add more lines.
 endef
-export FLAG     = $(shell cat challenge/flag.txt)
-export TAG      = CTFd tag
+export FLAG      = $(shell cat challenge/flag.txt)
+export TAG       = CTFd tag
 
 ############################
 # Deployment Configuration #
@@ -149,32 +149,42 @@ sbuild:
 	cd solution/ ; \
 	${RUNTIME} build -t ${REGISTRY}/${NAME}-solvescript ${SBARGS} .
 
+define run_check
+	cd solution/ ; \
+	echo -e	"\e[1;36m>>>>>>>>>>>>>> START $$(date +'%H:%M:%S')\e[0m"; \
+	exec 3>&1 ; \
+	O=$$(${RUNTIME} run --rm ${SRARGS} ${2} -e TICKET=${3} \
+	--name ${NAME}-solvescript${1} \
+		${REGISTRY}/${NAME}-solvescript 3>&- | tee /dev/fd/3) ; \
+	RETVAL=$$? ; \
+	exec 3>&- ; \
+	echo -e	"\e[1;36m<<<<<<<<<<<<<< END $$(date +'%H:%M:%S')\e[0m"; \
+	printf "$$O" | grep ${FLAG} > /dev/null 2>&1 && \
+		echo -e "\033[1;32m[+] Real flag found: ${FLAG}\033[0;0m" || ( \
+	printf "$$O" | grep ${FAKE_FLAG} > /dev/null 2>&1 && \
+		echo -e "\033[1;32m[+] Fake flag found: ${FAKE_FLAG}\033[0;0m" \
+		|| ([[ "$$RETVAL" -eq "0" ]] && \
+		echo -e "\033[1;31m[!] Flag not found\033[0;0m"; exit 1))
+endef
+
 srun:
 	@echo -e "\e[1;34m[+] Running Solvescript Container against" \
 		"${HOST}:${PORT}\e[0m"
-	${RUNTIME} run --rm ${SRARGS} -e TICKET=${SINGLE_TICKETS} -e VERBOSE="--verbose"\
-		--name ${NAME}-solvescript ${IT} ${REGISTRY}/${NAME}-solvescript
+	@$(call run_check,,-it,${SINGLE_TICKETS})
 
 TIMES=10
 TICKETS:= $(shell shuf -n ${TIMES} solution/tickets.txt | tr "\n" " ")
 srun-sequential:
 	@echo -e "\e[1;34m[+] Running Sequential Container against" \
 		"${HOST}:${PORT}\e[0m"
-	parallel --jobs 1 ${RUNTIME} run --rm ${SRARGS} \
-		${REGISTRY}/${NAME}-solvescript \
-		/usr/bin/timeout -k 5 ${TIMEOUT} python solve_challenge.py \
-			--host ${HOST} --port ${PORT} --ticket $1 \
-		::: ${TICKETS}
+	@parallel --line-buffer --jobs 1 '$(call run_check,-sequential-{},{},)' \
+ 		::: ${TICKETS}
 
-JOBS=2
+JOBS=4
 srun-parallel:
 	@echo -e "\e[1;34m[+] Running Parallel Container against ${HOST}:${PORT}\e[0m"
-	cd solution/ ; \
-	parallel --jobs ${JOBS} ${RUNTIME} run --rm ${SRARGS} \
-		${REGISTRY}/${NAME}-solvescript \
-		/usr/bin/timeout -k 5 ${TIMEOUT} python solve_challenge.py \
-			--host ${HOST} --port ${PORT} --ticket $1 \
-		::: ${TICKETS}
+	@parallel --jobs ${JOBS} '$(call run_check,-parallel-{},{},)' \
+ 		::: ${TICKETS}
 
 skill:
 	@echo -e "\e[1;34m[+] Killing Solution Container/s\e[0m"
