porting to all templates

diff --git a/solidity-nojail-debian11/Makefile b/solidity-nojail-debian11/Makefile
--- a/solidity-nojail-debian11/Makefile
+++ b/solidity-nojail-debian11/Makefile
@@ -96,7 +96,7 @@ ckill:
 	@echo -e "\e[1;34m[+] Killing Challenge Container\e[0m"
 	${RUNTIME} ps --filter "name=${NAME}" --format "{{.ID}}" \
 		| tr '\n' ' ' \
-		| xargs ${RUNTIME} stop -t 0 \
+		| xargs -r ${RUNTIME} stop -t 0 \
 		|| true
 
 ##########################
@@ -190,7 +190,7 @@ skill:
 	@echo -e "\e[1;34m[+] Killing Solution Container/s\e[0m"
 	${RUNTIME} ps --filter "name=${NAME}-solvescript*" --format "{{.ID}}" \
 		| tr '\n' ' ' \
-		| xargs ${RUNTIME} stop -t 0 \
+		| xargs -r ${RUNTIME} stop -t 0 \
 		|| true
 
 ########################
@@ -261,10 +261,11 @@ define test_solve_container
 		[ "`$1 ps --format 'UP' --filter "name=${NAME}"`" == "UP" ] && \
 		F='0' && break || sleep 1; \
 	done; \
-	[ "$$F" == "1" ] && echo -e "\e[1;31mTimeout reached\e[0m" && exit 1 || true 
+	[ "$$F" == "1" ] && (echo -e "\e[1;31mTimeout reached\e[0m" && make kill && \
+		exit 1) || true 
 	echo -e "[+] make solve" || true
 	@make solve >> $(TEST_LOG) 2>&1 && echo -e "\e[1;32m[+] Flag found\e[0m" || \
-		(echo -e "\e[1;33m[+] Flag not found\e[0m" && exit 1)
+		(echo -e "\e[1;33m[+] Flag not found\e[0m" && make kill && exit 1)
 endef
 
 define test_fail
